Gem::Specification.new do |s|
  s.name        = 'jcs3'
  s.version     = '0.0.0'
  s.date        = '2013-01-13'
  s.summary     = "Deploys a set of files to a AWS Cloudfront distribution backed by S3.  Great for deploying static sites like those generated by Jekyll"
  s.description = "A gem for deploying to an S3 backed Cloudfront distribution"
  s.authors     = ["Brandon Smith"]
  s.email       = 'brandon@tokengnome.com'
  s.homepage    = 'http://rubygems.org/gems/jcs3'

  s.add_runtime_dependency('aws-sdk', "~> 1.8.0")
  
  s.files = %w[
    Gemfile 
    jcs3.gemspec
    lib/jcs3.rb
    lib/jcs3/compressor.rb
    lib/jcs3/deployer.rb
  ]
end